// <auto-generated />
using System;
using IPA_Praesentationsverwaltung.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPA_Praesentationsverwaltung.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260623072215_AddSelectionConfirmedAt")]
    partial class AddSelectionConfirmedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IPA_Praesentationsverwaltung.Models.Domain.Presentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxObservers")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Presentations");
                });

            modelBuilder.Entity("IPA_Praesentationsverwaltung.Models.Domain.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PresentationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PresentationId");

                    b.HasIndex("StudentId", "PresentationId")
                        .IsUnique();

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("IPA_Praesentationsverwaltung.Models.Domain.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("IPA_Praesentationsverwaltung.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<int>("Role");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("IPA_Praesentationsverwaltung.Models.Domain.Admin", b =>
                {
                    b.HasBaseType("IPA_Praesentationsverwaltung.Models.Domain.User");

                    b.Property<bool>("CanManageSystem")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("IPA_Praesentationsverwaltung.Models.Domain.Student", b =>
                {
                    b.HasBaseType("IPA_Praesentationsverwaltung.Models.Domain.User");

                    b.Property<bool>("InitialPasswordSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SelectionConfirmedAt")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("IPA_Praesentationsverwaltung.Models.Domain.Presentation", b =>
                {
                    b.HasOne("IPA_Praesentationsverwaltung.Models.Domain.Room", "Room")
                        .WithMany("Presentations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("IPA_Praesentationsverwaltung.Models.Domain.Registration", b =>
                {
                    b.HasOne("IPA_Praesentationsverwaltung.Models.Domain.Presentation", "Presentation")
                        .WithMany("Registrations")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPA_Praesentationsverwaltung.Models.Domain.Student", "Student")
                        .WithMany("Registrations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IPA_Praesentationsverwaltung.Models.Domain.Presentation", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("IPA_Praesentationsverwaltung.Models.Domain.Room", b =>
                {
                    b.Navigation("Presentations");
                });

            modelBuilder.Entity("IPA_Praesentationsverwaltung.Models.Domain.Student", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
